CREATE TABLE "GCG_6752_SETTINGS" (
 "REC_ID" INTEGER,
 "REMOTEHOST" CHAR(50),
 "REMOTEUSER" CHAR(50),
 "REMOTEPASSWORD" CHAR(50),
 "REMOTEPORT" CHAR(50),
 "REMOTEPATH" CHAR(150),
 "DATE_LAST_CHG" CHAR(8),
 "TIME_LAST_CHG" CHAR(8),
 "PID" INTEGER,
 "DEL_FILE" CHAR(1),
 "PAYCOM_TO_GSS" CHAR(1),
 "USER_ID_ERROR" CHAR(50) );